### ISSUE TITLE
Need to modify filterQuality

### ISSUE THREAD

**Issue by dragonfax** [spritewidget/spritewidget#66] opened 2020-10-25 04:54 UTC
I'm using pixel art. Very low res sprites. And without setting the filterQuality on the Paint() object to 'none' they end up looking like trash. I forked just to make this one change to the code base.

I know the project is dead, but I figured I'd create this issue to document the need.

**Comment by vlidholt** [comment] 2022-04-22 08:38
Duplicate of #34 

Closing this one, but issue is tracked.

**Closed by vlidholt** 2022-04-22 08:38 UTC
Labels: enhancement
