### ISSUE TITLE
library not compatible with latest flutter dev version

### ISSUE THREAD

**Issue by torvalde** [spritewidget/spritewidget#47] opened 2019-05-28 12:29 UTC
Running with flutter version:

`~ flutter --version
Flutter 1.6.3 • channel dev • https://github.com/flutter/flutter.git
Framework • revision bc7bc94083 (5 days ago) • 2019-05-23 10:29:07 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)`

Error:

> Compiler message:
> /spritewidget-0.9.18/lib/src/image_map.dart:31:29: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
>  - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('/image_stream.dart').
>  - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('/image_stream.dart').
> Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
>       stream.removeListener(listener);
>                             ^
> image_map.dart:33:24: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
>  - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('/image_stream.dart').
>  - '/image_stream.dart' ('/image_stream.dart').
> Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
>     stream.addListener(listener);

**Comment by squashmode** [comment] 2019-06-03 12:46
Confirmed here.  This is a blocker, should be pretty easy to fix.

Is this project being maintained anymore?  Is anyone maintaining a fork that is up to date?

**Comment by vlidholt** [comment] 2019-06-04 09:09
Will look into this!

**Comment by squashmode** [comment] 2019-06-04 12:28
Thank you. 
Looks like flutter added a few typedefs that need to be used, I ended up doing something like this:
```
diff --git a/lib/src/image_map.dart b/lib/src/image_map.dart
index 4e48f16..926994d 100644
--- a/lib/src/image_map.dart
+++ b/lib/src/image_map.dart
@@ -22,15 +21,16 @@ class ImageMap {

   /// Loads a single image given the image's [url] and adds it to the [ImageMap].
   Future<ui.Image> loadImage(String url) async {
-    ImageStream stream = new AssetImage(url, bundle: _bundle).resolve(ImageConfiguration.empty);
-    Completer<ui.Image> completer = new Completer<ui.Image>();
-    void listener(ImageInfo frame, bool synchronousCall) {
+    ImageStream stream = AssetImage(url, bundle: _bundle).resolve(ImageConfiguration.empty);
+    Completer<ui.Image> completer = Completer<ui.Image>();
+    ImageStreamListener isl;
+    isl = ImageStreamListener((ImageInfo frame, bool synchronousCall) {
       final ui.Image image = frame.image;
       _images[url] = image;
       completer.complete(image);
-      stream.removeListener(listener);
-    }
-    stream.addListener(listener);
+      stream.removeListener(isl);
+    });
+    stream.addListener(isl);
     return completer.future;
   }
```

**Comment by jackylope** [comment] 2019-06-05 17:55
@vlidholt Any update on a fix for this? I'm itching to get developing!

@squashmode I tried using your fix in image_map.dart but i'm still getting a compiler error because its saying ImageStreamListener is not a type. 

``
file:///home/jackylope/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/spritewidget-0.9.18/lib/src/image_map.dart:17:3: Error: Type 'ImageStreamListener' not found.
  ImageStreamListener isl;
  ^^^^^^^^^^^^^^^^^^^
file:///home/jackylope/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/spritewidget-0.9.18/lib/src/image_map.dart:17:3: Error: 'ImageStreamListener' isn't a type.
  ImageStreamListener isl;
  ^^^^^^^^^^^^^^^^^^^
file:///home/jackylope/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/spritewidget-0.9.18/lib/src/image_map.dart:27:5: Error: 'ImageStreamListener' isn't a type.
    ImageStreamListener isl;
    ^^^^^^^^^^^^^^^^^^^
file:///home/jackylope/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/spritewidget-0.9.18/lib/src/image_map.dart:28:11: Error: Method not found: 'ImageStreamListener'.
    isl = ImageStreamListener((ImageInfo frame, bool synchronousCall) {
          ^^^^^^^^^^^^^^^^^^^
file:///home/jackylope/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/spritewidget-0.9.18/lib/src/image_map.dart:28:11: Error: The method 'ImageStreamListener' isn't defined for the class 'ImageMap'.
 - 'ImageMap' is from 'package:spritewidget/spritewidget.dart' ('file:///home/jackylope/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/spritewidget-0.9.18/lib/spritewidget.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageStreamListener'.
    isl = ImageStreamListener((ImageInfo frame, bool synchronousCall) {
          ^^^^^^^^^^^^^^^^^^^
Compiler failed on /home/jackylope/AndroidStudioProjects/space_control/lib/main.dart
Gradle task assembleDebug failed with exit code 1``

**Comment by jackylope** [comment] 2019-06-05 18:08
Oops, looks like i was encountering a brain fart and didn't update Flutter.

**Comment by drost** [comment] 2019-06-18 21:01
I just made a merge request for this fix, since it hasn't been fixed yet.

**Comment by vlidholt** [comment] 2022-04-22 07:52
Fixed

**Closed by vlidholt** 2022-04-22 07:52 UTC
